package wwise

var PropLabel_140 = []string{
  "Volume",
  "LFE",
  "Pitch",
  "LPF",
  "HPF",
  "Bus Volume",
  "Make Up Gain",
  "Priority",
  "Priority Distance Offset",
  "Feedback Volume (Unused)",
  "Feedback LPF (Unused)",
  "Mute Ratio",
  "PAN LR",
  "PAN FR",
  "Center PCT",
  "Delay Time",
  "Transition Time",
  "Probability",
  "Dialogue Mode",
  "User AuxSend Volume 0",
  "User AuxSend Volume 1",
  "User AuxSend Volume 2",
  "User AuxSend Volume 3",
  "Game Aux Send Volume",
  "Output Bus Volume",
  "Output Bus HPF",
  "Output Bus LPF",
  "HDR Bus Threshold",
  "HDR Bus Ratio",
  "HDR Bus Release Time",
  "HDR Bus Game Param",
  "HDR Bus Game Param Min",
  "HDR Bus Game Param Max",
  "HDR Active Range",
  "Loop Start",
  "Loop End",
  "Trim In Time",
  "Trim Out Time",
  "Fade In Time",
  "Fade Out Time",
  "Fade In Curve",
  "Fade Out Curve",
  "Loop Crossfade Duration",
  "Crossfade Up Curve",
  "Crossfade Down Curve",
  "Midi Tracking Root Note",
  "Midi Play On Note Type",
  "Midi Transposition",
  "Midi Velocity Offset",
  "Midi Key Range Min",
  "Midi Key Range Max",
  "Midi Velocity Range Min",
  "Midi Velocity Range Max",
  "Midi Channel Mask",
  "Playback Speed",
  "Midi Tempo Source",
  "Midi Target Node",
  "Attached Plugin FX ID",
  "Loop",
  "Initial Delay",
  "User Aux Send LPF 0",
  "User Aux Send LPF 1",
  "User Aux Send LPF 2",
  "User Aux Send LPF 3",
  "User Aux Send HPF 0",
  "User Aux Send HPF 1",
  "User Aux Send HPF 2",
  "User Aux Send HPF 3",
  "Game Aux Send LPF",
  "Game Aux Send HPF",
  "Attenuation ID",
  "Positioning Type Blend",
  "Reflection Bus Volume",
  "PAN_UD",
}

