// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package id

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.hierarchyIdStmt, err = db.PrepareContext(ctx, hierarchyId); err != nil {
		return nil, fmt.Errorf("error preparing query HierarchyId: %w", err)
	}
	if q.insertHierarchyStmt, err = db.PrepareContext(ctx, insertHierarchy); err != nil {
		return nil, fmt.Errorf("error preparing query InsertHierarchy: %w", err)
	}
	if q.insertSourceStmt, err = db.PrepareContext(ctx, insertSource); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSource: %w", err)
	}
	if q.sourceIdStmt, err = db.PrepareContext(ctx, sourceId); err != nil {
		return nil, fmt.Errorf("error preparing query SourceId: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.hierarchyIdStmt != nil {
		if cerr := q.hierarchyIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hierarchyIdStmt: %w", cerr)
		}
	}
	if q.insertHierarchyStmt != nil {
		if cerr := q.insertHierarchyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertHierarchyStmt: %w", cerr)
		}
	}
	if q.insertSourceStmt != nil {
		if cerr := q.insertSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSourceStmt: %w", cerr)
		}
	}
	if q.sourceIdStmt != nil {
		if cerr := q.sourceIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing sourceIdStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                  DBTX
	tx                  *sql.Tx
	hierarchyIdStmt     *sql.Stmt
	insertHierarchyStmt *sql.Stmt
	insertSourceStmt    *sql.Stmt
	sourceIdStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                  tx,
		tx:                  tx,
		hierarchyIdStmt:     q.hierarchyIdStmt,
		insertHierarchyStmt: q.insertHierarchyStmt,
		insertSourceStmt:    q.insertSourceStmt,
		sourceIdStmt:        q.sourceIdStmt,
	}
}
