// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: id_insert.sql

package id

import (
	"context"
)

const insertHierarchy = `-- name: InsertHierarchy :exec
INSERT INTO hierarchy (hid) VALUES (?)
`

func (q *Queries) InsertHierarchy(ctx context.Context, hid int64) error {
	_, err := q.exec(ctx, q.insertHierarchyStmt, insertHierarchy, hid)
	return err
}

const insertSource = `-- name: InsertSource :exec
INSERT INTO source (sid) VALUES (?)
`

func (q *Queries) InsertSource(ctx context.Context, sid int64) error {
	_, err := q.exec(ctx, q.insertSourceStmt, insertSource, sid)
	return err
}
