// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: id_query.sql

package id

import (
	"context"
)

const hierarchyId = `-- name: HierarchyId :one
SELECT COUNT(*) FROM hierarchy WHERE hid = ?
`

func (q *Queries) HierarchyId(ctx context.Context, hid int64) (int64, error) {
	row := q.queryRow(ctx, q.hierarchyIdStmt, hierarchyId, hid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sourceId = `-- name: SourceId :one
SELECT COUNT(*) FROM source WHERE sid = ?
`

func (q *Queries) SourceId(ctx context.Context, sid int64) (int64, error) {
	row := q.queryRow(ctx, q.sourceIdStmt, sourceId, sid)
	var count int64
	err := row.Scan(&count)
	return count, err
}
